import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
    inputResult: {
        color: 'white',
        fontSize: 41,
        padding: 10,
        marginTop: 'auto',
        textAlign: 'right',
        marginHorizontal: '10%',
    },
    btnRow: {
        flexDirection: 'row',
        marginVertical: 3,
    },
    btnWhite: {
        color: 'white',
        fontSize: 17,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 30,
        backgroundColor: "#262626",
        borderRadius: 50,
        margin: 5,
        marginVertical: 0,
    },
    btnGreen: {
        color: "#4ade80",
        fontSize: 17,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 30,
        backgroundColor: "#262626",
        borderRadius: 50,
        margin: 5,
        marginVertical: 0,
    },
    btnRed: {
        color: "#f87171",
        fontSize: 17,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 30,
        backgroundColor: "#262626",
        borderRadius: 50,
        margin: 5,
        marginVertical: 0,
    },
    btnEqual: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
        fontSize: 17,
        fontWeight: 'bold',
        padding: 30,
        backgroundColor: "#4ade80",
        borderRadius: 50,
        margin: 5,
        marginVertical: 0,
    },
});